# Generated by Django 3.2.7 on 2021-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ame', models.CharField(max_length=30)),
                ('e_mail', models.CharField(max_length=20)),
                ('a_ddress', models.CharField(max_length=50)),
                ('p_wd', models.CharField(max_length=20)),
            ],
        ),
    ]
