# Generated by Django 3.2.7 on 2021-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='m_obile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='e_mail',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='p_wd',
            field=models.CharField(max_length=30),
        ),
    ]
