# Generated by Django 3.2.7 on 2021-09-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210914_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registermodel',
        ),
    ]
