# Generated by Django 3.2.7 on 2021-09-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_registermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='g_ender',
        ),
    ]
