# Generated by Django 3.2.7 on 2021-09-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_registermodel_g_ender'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_hoto', models.ImageField(upload_to='app/static')),
            ],
        ),
    ]
