# Generated by Django 3.2.7 on 2021-09-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_updatemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updatemodel',
        ),
    ]
