# Generated by Django 3.2.7 on 2021-09-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_updatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_hoto', models.ImageField(upload_to='app/static')),
                ('n_ame', models.CharField(max_length=30)),
                ('m_obile', models.IntegerField()),
                ('a_ddress', models.CharField(max_length=50)),
            ],
        ),
    ]
